import { ArrowLeft, ArrowRight, Bot, CircleAlert, FileSearch, HeartHandshake, Lightbulb, LockKeyhole, MessageSquareText, Sparkles, X } from 'lucide-react'
import { useLayoutEffect, useRef } from 'react'
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion'
import { SiteHeader } from '../components/SiteHeader'
import { AiCitations, AiModeNav, AiSourceRegister, AiStatusStamp, WorkflowStrip } from '../components/AiTeaching'
import { chapters, horizons, taskLens } from '../data/aiContent'
import cerebralHeroArt from '../assets/ai-cerebral-hero.webp'
import consultationArt from '../assets/ai-consultation.webp'
import verificationArt from '../assets/ai-verification.webp'
import futureArt from '../assets/ai-future-horizons.webp'
import educationArt from '../assets/ai-education-workflow.webp'
import taskLandscapeArt from '../assets/ai-task-landscape.webp'

function ChapterHeader({ number, eyebrow, children }: { number: string; eyebrow: string; children: React.ReactNode }) {
  return <header><span>{number}</span><div><p className="eyebrow">{eyebrow}</p><h2>{children}</h2></div></header>
}

export function AiMedicinePage() {
  const reduceMotion = useReducedMotion()
  const { scrollYProgress } = useScroll()
  const progressOpacity = useTransform(scrollYProgress, [0, .02], [.2, 1])
  const hero = useRef<HTMLElement>(null)
  const { scrollYProgress: heroProgress } = useScroll({ target: hero, offset: ['start start', 'end start'] })
  const heroImageY = useTransform(heroProgress, [0, 1], [0, reduceMotion ? 0 : 90])

  useLayoutEffect(() => {
    const targets = Array.from(document.querySelectorAll<HTMLElement>('.ai-learn-page .learning-section > header, .ai-learn-page .learning-prose > *, .ai-learn-page .learning-cta > *'))
    targets.forEach((target, index) => {
      target.classList.add('ai-reveal')
      target.style.setProperty('--ai-reveal-delay', `${Math.min(index % 4, 3) * 70}ms`)
    })
    if (reduceMotion) {
      targets.forEach((target) => target.classList.add('is-visible'))
      return () => targets.forEach((target) => target.classList.remove('ai-reveal', 'is-visible'))
    }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.target.classList.toggle('is-visible', entry.isIntersecting)), { threshold: .12, rootMargin: '-8% 0px -18% 0px' })
    targets.forEach((target) => observer.observe(target))
    return () => observer.disconnect()
  }, [reduceMotion])

  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="scroll-progress" aria-hidden="true"><motion.span style={{ scaleX: scrollYProgress, opacity: reduceMotion ? 1 : progressOpacity }} /></div>
    <SiteHeader homeHref="../../" compact />
    <main id="main" className="ai-learn-page">
      <section className="ai-hero" ref={hero}>
        <motion.img className="ai-hero__backdrop" src={cerebralHeroArt} alt="" aria-hidden="true" style={{ y: heroImageY }} initial={reduceMotion ? false : { opacity: .18, scale: 1.015 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.05, ease: [0.22, 1, 0.36, 1] }} />
        <div className="ai-hero__scrim" />
        <div className="learn-hero__topline"><a className="back-link" href="../../"><ArrowLeft size={17} aria-hidden="true" /> All topics</a><AiModeNav mode="learn" /></div>
        <div className="ai-hero__grid">
          <motion.div initial={reduceMotion ? false : { opacity: 0, y: 28, filter: 'blur(3px)' }} animate={{ opacity: 1, y: 0, filter: 'none' }} transition={{ duration: .82, ease: [0.22, 1, 0.36, 1] }}>
            <p className="eyebrow">Learning guide · AI in Australian general practice</p>
            <h1>AI in<br /><span className="sr-only"> </span><em>Medicine</em></h1>
            <p>Follow one patient through a clinician’s working day—and learn where AI can assist without inheriting clinical judgement.</p>
            <AiStatusStamp dark />
          </motion.div>
        </div>
      </section>

      <section className="learning-disclaimer" aria-label="Scope and review note"><strong>Educational draft</strong><p>Current Australian guidance was checked on 12 July 2026. Clinical, legal/privacy, consumer and Aboriginal and Torres Strait Islander review remain required before publication or presentation. This is not individual medical, legal, privacy, procurement or cyber-security advice.</p></section>

      <div className="learning-layout">
        <nav className="contents-nav" aria-label="On this page"><p>One patient · one working day</p>{chapters.map(([id, label], index) => <a key={id} href={`#${id}`}><span>{String(index + 1).padStart(2, '0')}</span>{label}</a>)}</nav>
        <div className="learning-content">
          <section className="learning-section ai-question" id="question"><ChapterHeader number="01" eyebrow="Begin with the tension">Will AI take our jobs?</ChapterHeader><div className="learning-prose"><p className="lead">AI can already produce notes, differential lists, evidence summaries, patient fact sheets, presentations and flashcards. Is producing those artefacts the same as practising medicine?</p><blockquote className="opening-reflection">Hold your starting answer in mind. We will return to it after following one patient through a clinician’s working day.</blockquote></div></section>

          <section className="learning-section" id="michael"><ChapterHeader number="02" eyebrow="Before the tool">Meet Michael</ChapterHeader><div className="learning-prose"><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={consultationArt} alt="Michael, a fictional patient, speaking with his GP in a calm consultation" /></figure><div className="michael-card michael-card--text"><div><p className="section-tag">Fictional case · no real patient represented</p><h3>Michael, 64</h3><p>Known benign prostatic hyperplasia. Worsening urinary frequency and nocturia. He also mentions fatigue, increased thirst, and the effect on sleep, work and confidence.</p><blockquote>“How well does prostate artery embolisation work?”</blockquote></div></div><div className="anchor-prompt"><Lightbulb aria-hidden="true" /><div><strong>Form your view first.</strong><p>What fits the known BPH? What does not fit? What serious or easily missed possibility must stay visible?</p></div></div><p>Known BPH creates an easy anchor. The clinician’s first task is still to listen for what does not fit and decide what needs examination and investigation.</p></div></section>

          <section className="learning-section" id="scribe"><ChapterHeader number="03" eyebrow="During the consultation">The AI scribe</ChapterHeader><div className="learning-prose"><WorkflowStrip /><p className="lead">Lyrebird is named here once as the presenter’s personal example—not an endorsement. Its stated function is to capture a consultation and draft documentation for clinician review. <AiCitations sources={['S23']} /></p><aside className="consent-example"><p className="section-tag">Plain-language consent example</p><blockquote>“I use a tool that listens to our conversation and drafts a note for me to check. I remain responsible for the final record. You do not have to agree, and saying no will not change your care—I can take notes normally.”</blockquote><p className="qualification">Recording, consent and privacy requirements vary. Follow current practice policy, jurisdictional law and MDO or legal advice. <AiCitations sources={['S1', 'S2', 'S7']} /></p></aside><div className="scribe-columns"><article><Bot aria-hidden="true" /><h3>The tool can assist</h3><ul><li>Capture spoken details</li><li>Structure a draft note</li><li>Reduce retyping</li><li>Draft documents</li></ul></article><article><HeartHandshake aria-hidden="true" /><h3>The clinician must still</h3><ul><li>Manage consent and privacy</li><li>Notice non-verbal information</li><li>Examine and reason</li><li>Authorise the final record</li></ul></article></div><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={verificationArt} alt="Layered paper fragments being checked against a clinician-patient conversation" /></figure><div className="output-review"><div className="output-review__head"><div><p className="section-tag">Synthetic draft · worked review</p><h3>What is wrong—and what is missing?</h3></div></div><p>Reports nocturia and urinary frequency. Fatigue and thirst discussed. Abdomen soft and non-tender. Plan: continue current BPH treatment and routine review.</p><div className="review-findings"><p><X aria-hidden="true" /><span><strong>Unsupported:</strong> no abdominal examination occurred.</span></p><p><CircleAlert aria-hidden="true" /><span><strong>Missing:</strong> the effect on sleep, work and confidence—and a plan to investigate symptoms that do not fit.</span></p></div></div><p>Ambient scribes show promising workflow and clinician-experience signals in some outpatient settings, but benefits vary, manual correction is common and Australian patient-outcome evidence remains limited. <AiCitations sources={['S9', 'S10', 'S11', 'S12']} /></p></div></section>

          <section className="learning-section learning-section--ink" id="thinking"><ChapterHeader number="04" eyebrow="After an independent assessment">An educational thinking partner</ChapterHeader><div className="learning-prose"><WorkflowStrip active={2} /><p className="lead">The safe sequence is human reasoning first, AI challenge second, authoritative verification third.</p><div className="thinking-comparison"><article><p className="section-tag">Human view first</p><h3>What are you considering?</h3><p>Start with Michael’s story, examination and an independently formed assessment. Keep the known BPH visible without allowing it to explain symptoms that do not fit.</p></article><article><p className="section-tag">Fictional AI challenge</p><h3>Compare—do not defer</h3><p><strong>Common:</strong> progression of lower urinary tract symptoms; fluid or medicine effects; sleep-related causes.</p><p><strong>Serious or easily missed:</strong> diabetes mellitus; urinary infection or retention; renal impairment; other systemic causes of polyuria or fatigue.</p><p><strong>Check rather than copy:</strong> chronology, medicines, fluid intake, weight change, infection features, examination, urinalysis and appropriately selected investigations.</p></article></div><div className="safety-banner"><LockKeyhole aria-hidden="true" /><p><strong>Educational use only.</strong> Do not enter identifiable patient information into a public general-purpose AI tool. Do not use this exercise as individual medical advice. <AiCitations sources={['S6']} /></p></div><p>Subsequent ordinary assessment and investigation confirm that Michael also has type 2 diabetes. The AI did not make the diagnosis. In one randomised vignette study, LLM access did not significantly improve physician diagnostic reasoning over conventional resources. <AiCitations sources={['S14']} /></p></div></section>

          <section className="learning-section" id="evidence"><ChapterHeader number="05" eyebrow="A synthesis is not a source">Finding an evidence-based answer</ChapterHeader><div className="learning-prose"><WorkflowStrip active={3} /><blockquote className="question-quote">“How well does prostate artery embolisation work?”</blockquote><p>MedLuma is the presenter’s current retrieval example, not a recommendation. Its first-party description says it uses a curated knowledge base and links to original sources. That description establishes functionality, not clinical benefit. <AiCitations sources={['S22']} /></p><ol className="evidence-ladder"><li><span>1</span><div><h3>Define “work”</h3><p>Symptom relief, quality of life, complications, retreatment—or something else?</p></div></li><li><span>2</span><div><h3>Inspect the frame</h3><p>Population, comparator, outcome and follow-up duration.</p></div></li><li><span>3</span><div><h3>Open the source</h3><p>Read the cited guideline or paper; do not cite the synthesis as evidence.</p></div></li><li><span>4</span><div><h3>Translate, do not paste</h3><p>Relate evidence to Michael’s priorities, anatomy, comorbidities and alternatives.</p></div></li></ol><p className="qualification-note"><strong>No numerical answer is given here.</strong> Prostate artery embolisation efficacy was not separately researched for this lesson.</p></div></section>

          <section className="learning-section" id="patient-info"><ChapterHeader number="06" eyebrow="Generation is the beginning">Drafting patient information</ChapterHeader><div className="learning-prose"><WorkflowStrip active={4} /><div className="placeholder-sheet"><span>Placeholder</span><FileSearch aria-hidden="true" /><h3>Reviewed type 2 diabetes patient fact sheet</h3><p>To be sourced, clinically reviewed and consumer reviewed before publication.</p><a href="https://education.alexanderqho.com" target="_blank" rel="noreferrer">education.alexanderqho.com <small>Site in development</small></a></div><ol className="editorial-flow"><li>Select Australian authoritative sources.</li><li>Specify audience, purpose, reading level and actions.</li><li>Generate a draft or alternative explanation.</li><li>Check every claim and link against the source.</li><li>Review readability, inclusivity, accessibility and safety-netting.</li><li>Obtain consumer review and publish only the clinician-approved version.</li></ol><p>AI may assist drafting or simplification, but readability can improve or worsen, and accuracy, completeness and actionability still need review. <AiCitations sources={['S24']} /></p></div></section>

          <section className="learning-section" id="education"><ChapterHeader number="07" eyebrow="After clinic">Make learning objects—not plausible clutter</ChapterHeader><div className="learning-prose"><WorkflowStrip /><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={educationArt} alt="A clinician-educator moving from source appraisal to presentation and study-card development" /></figure><div className="education-grid"><article><Sparkles aria-hidden="true" /><h3>Research and presentation</h3><p>Frame the question, challenge the outline, locate original sources, read them, separate sourced claims from interpretation and placeholders, then edit the final narrative.</p></article><article><MessageSquareText aria-hidden="true" /><h3>Anki cards</h3><p>Provide selected source material, keep one learning point per card, check every qualifier and delete cards that are trivial, ambiguous or wrong.</p></article></div><div className="card-quality"><article><span>Useful</span><p>What five actions make up the recurring AI workflow?</p><strong>Define · Protect · Generate · Verify · Own</strong></article><article><span>Ambiguous</span><p>What is the best AI tool in medicine?</p><strong>No defined task, version, population or outcome.</strong></article><article><span>Confidently wrong</span><p>True or false: human review makes any AI output safe.</p><strong>False framing: review must be informed, timely and feasible.</strong></article></div><p>Reviews identify educator productivity and learner-support uses alongside inaccurate content, misuse and AI-literacy needs. <AiCitations sources={['S25', 'S26']} /></p></div></section>

          <section className="learning-section" id="landscape"><ChapterHeader number="08" eyebrow="Start with the task, not the label">AI beyond this workflow</ChapterHeader><div className="learning-prose"><p className="lead">A scribe, an image classifier and a treatment recommendation are not one intervention. They have different inputs, users, evidence and failure consequences. <AiCitations sources={['S3', 'S21']} /></p><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={taskLandscapeArt} alt="Distinct medical AI tasks arranged around a central clinical team" /></figure><div className="task-constellation">{['Documentation', 'Screening & imaging', 'Defined decision support', 'Surgical assistance', 'Patient support', 'Record analysis', 'Remote monitoring'].map((item, index) => <div key={item} style={{ '--i': index } as React.CSSProperties}>{item}</div>)}</div><div className="task-lens"><p className="section-tag">TASK · teaching synthesis developed for this lesson</p>{taskLens.map(([letter, title, detail]) => <article key={letter}><span>{letter}</span><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div></div></section>

          <section className="learning-section" id="future"><ChapterHeader number="09" eyebrow="Possibilities, not promises">Three horizons</ChapterHeader><div className="learning-prose"><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={futureArt} alt="A clinician and patient walking together through a landscape of branching future paths" /></figure><div className="horizon-grid">{Object.values(horizons).map((item) => <article key={item.label}><p className="status-label">{item.status}</p><h3>{item.label}</h3><ul>{item.items.map((use) => <li key={use}>{use}</li>)}</ul></article>)}</div><div className="horizon-questions"><h3>Interrogate every horizon</h3><ol><li>What becomes easier?</li><li>What new failure becomes possible?</li><li>Who responds when it is wrong or silent?</li><li>What human capability must be protected?</li></ol></div><p>The further a system moves from drafting toward autonomous action, the higher the evidence and governance bar should become.</p></div></section>

          <section className="learning-section ai-human" id="human"><ChapterHeader number="10" eyebrow="Return to the opening question">What remains human?</ChapterHeader><div className="learning-prose"><p className="lead">Probably not—but AI will reshape many tasks. It can generate useful artefacts. It does not inherit accountability or create a therapeutic relationship simply by producing empathetic words.</p><figure className="ai-editorial-art ai-editorial-art--chapter"><img src={futureArt} alt="A clinician and patient continuing together along a branching path" /></figure><div className="human-columns"><article><Bot aria-hidden="true" /><h3>AI can help generate</h3><ul><li>Notes and summaries</li><li>Lists and suggestions</li><li>Evidence syntheses</li><li>Patient-information drafts</li><li>Learning resources</li></ul></article><article><HeartHandshake aria-hidden="true" /><h3>The clinician must provide</h3><ul><li>Judgement and accountability</li><li>Context and prioritisation</li><li>Critical appraisal and shared decisions</li><li>Listening, explanation and reassurance</li><li>Curiosity, reflection and competence</li></ul></article></div><blockquote>Use AI for the work it can assist with. Keep hold of the work that makes care safe, trustworthy and human.</blockquote></div></section>

          <section className="learning-section" id="sources"><ChapterHeader number="11" eyebrow="Trace the authority">Sources and review</ChapterHeader><div className="learning-prose"><p className="lead">This guide draws on a targeted rapid review, not a systematic review. Product pages describe functionality only; they are not evidence of benefit.</p><div className="review-warning"><CircleAlert aria-hidden="true" /><p><strong>Not publication-ready.</strong> Recheck current regulator and professional guidance, then obtain the outstanding clinical, legal/privacy, consumer and Aboriginal and Torres Strait Islander reviews.</p></div><AiSourceRegister /></div></section>
        </div>
      </div>
      <section className="learning-cta"><p className="eyebrow">One patient · ten scenes</p><h2>Ready for the room?</h2><p>Open the click-free 35-minute presentation and move through it by scrolling or using the arrow keys.</p><a className="button button--primary" href="./presentation/">Present this topic <ArrowRight size={18} aria-hidden="true" /></a></section>
    </main>
    <footer className="site-footer"><span className="footer-brand">Dr Alexander Ho</span><span>AI in Medicine · Australian learning guide</span><span>Current as at 12 July 2026</span></footer>
  </>
}
